server:
  port: 8080
jwt:
  secret:
    secret
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: 'root'
    password: '@Div2000'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

application:
  name: Login
  